version: "3"
services:
  certbot:
    image: certbot/certbot
    container_name: nginx-certbot
    volumes:
      - ./dockerdata/certbot/conf:/etc/letsencrypt
      - ./dockerdata/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx-alpine/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=$BASE_HOSTNAME
      # set environment variable in override from # to empty to activate
      - BASEAUTH=#
      - PORTFOLIO=#
    volumes:
      - ./templates:/etc/nginx/templates
      - ./conf.d/includes:/etc/nginx/i
      - ./logs:/var/log/nginx
      - ./dockerdata/certbot/conf:/etc/letsencrypt
      - ./dockerdata/certbot/www:/var/www/certbot
      - ./bs:/base-static
    restart: always

  nginx-cron:
    image: paradoxon/alpine-cron
    container_name: nginx-cron
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/cron/crontab:/tmp/crontab
    network_mode: "none"
    restart: always
