version: '3'
services:
  nginx:
    # environment:
      # activate the following (empty) environment variables to activate those services
      # - BASEAUTH=
      # - PORTFOLIO=
      # if the root URI "/" should redirect to an app (e.g. portfolio), uncomment this and set it to /portfolio
      # - INDEX_REDIRECT=/
    volumes:
      - $PORTFOLIO_FRONTEND:/portfolio-frontend
      - $PORTFOLIO_STATIC:/portfolio-static
      - $PORTFOLIO_MEDIA:/portfolio-media
      - $PORTFOLIO_PROTECTED:/portfolio-protected
    networks:
      baseauth_baseauthnet:
        aliases:
          - $BASE_HOSTNAME
      portfolio-backend_portfolionet:
        aliases:
          - $BASE_HOSTNAME
networks:
  baseauth_baseauthnet:
    external: true
  portfolio-backend_portfolionet:
    external: true
