version: '3'
services:
  nginx:
    # environment:
    #  -
    volumes:
      - $PORTFOLIO_FRONTEND:/portfolio-frontend
      - $PORTFOLIO_STATIC:/portfolio-static
      - $PORTFOLIO_MEDIA:/portfolio-media
      - $PORTFOLIO_PROTECTED:/portfolio-protected
    networks:
      baseauth_baseauthnet:
        aliases:
          - $BASE_HOSTNAME
      portfolio-backend_portfolionet:
        aliases:
          - $BASE_HOSTNAME
networks:
  baseauth_baseauthnet:
    external: true
  portfolio-backend_portfolionet:
    external: true
