location /showroom/s/ {
  alias /showroom-static/;
}

location ~ ^/showroom/((api|accounts|da|docs)/|sitemap.*\.xml) {
  rewrite ^/showroom/(.*) /$1 break;
  proxy_pass http://showroom-django;
  include i/proxy.conf;
}

location /showroom {
  proxy_pass http://showroom-frontend;
  include i/proxy.conf;
}
